[package]
name = "quiteville"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quad-rand = "0.1"

[profile.release]
opt-level = "z"
lto = true
